# Generated by Django 4.0.6 on 2022-07-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_publc',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
