# Generated by Django 4.0.6 on 2022-07-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_post_is_publc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_publc',
            new_name='is_public',
        ),
    ]
